### ISSUE TITLE
Missing documentation on how to set up database

### ISSUE THREAD

**Issue by e-shirt** [Holenstein-Ingenieure-AG/lrs-editor#1]
I'm missing a more extensive documentation on how to set up the database for the editor.

Do I have to add all given tables shown in 10.1 to the db first before setting up a connection via editor or does the editor add some of the tables itself?
I cannot seem to connect to/create a basesystem. When/Where do I add my given geometries that I want to work on?

I am not able to insert UUID fields via QGIS>New table... as QGIS seems to not support that provider type. So is it neccesary to add tables via pg directly?

**Comment by meier-r** [comment]
In advance you need to add or create two classes as a Base System in your PostGIS-Database, as described in chapters 3 and 6.3:

- Base Class (LineStrings) with a field for the route id (character/text)
- Point Class (Points) with three fields: route id (character/text), sort number (integer/float) for multipart routes, point type field (integer/float)

The plugin creates dynamically the routes of your Base System. If you have multipart routes, you need to give for every part the correct sort number in direction of the route. If you have singlepart routes, sort number is always '1'. The point type defines the direction of the route part.

All other tables as described in 10.1 are created and managed by the plugin itself. You need only to provide a connection in QGIS to the database, where your Base System is and where the LRS-Project should be managed.

**Comment by e-shirt** [comment]
Thanks for your hints, but they still do not really answer my questions in the issue above. I try to be more detailled:

First I create the project table:
![image](https://github.com/Holenstein-Ingenieure-AG/lrs-editor/assets/88319901/7bff6077-155c-41aa-a2cb-1b95fcad40b5)

 
Then I create the basesystem table:
![image](https://github.com/Holenstein-Ingenieure-AG/lrs-editor/assets/88319901/3e8f35a3-6bac-4365-bbc4-5e08c1a6cbc2)

 
Then I create the event class table:
![image](https://github.com/Holenstein-Ingenieure-AG/lrs-editor/assets/88319901/633341b6-322c-4355-9cf6-32b6c922814b)

 
And route class:
![image](https://github.com/Holenstein-Ingenieure-AG/lrs-editor/assets/88319901/0cf67576-61e8-4518-8187-f9924025b3b3)

 
And check class:
![image](https://github.com/Holenstein-Ingenieure-AG/lrs-editor/assets/88319901/ebaf39c4-112d-4e6f-bbde-54c149cfc5ec)

I am not able to set up a UUID, as that is not an available option when creating a new schema in QGIS. AFAIK, UUID is not supported by PostGIS in QGIS at all. I suspect I will be able to set a UUID later via attribute form if necessary.
According to documentation, I am now supposed to create a point class. I am not able to as there is no layer to choose.

So I first edit the project settings as given in manual to create a project. Connection to database and schema work fine, giving it any name, setting any logfile paths, giving any name for route class
![image](https://github.com/Holenstein-Ingenieure-AG/lrs-editor/assets/88319901/c08bdc3c-dcda-4cc3-b877-96db9136adcc)

Table „routes“ gets automatically created with linestring geometries, set to EPSG:25832 with the following properties:
![image](https://github.com/Holenstein-Ingenieure-AG/lrs-editor/assets/88319901/19e37de3-2123-4124-897d-492a6874e2a1)

 
This newly created table is now available to choose for creating a point class:
![image](https://github.com/Holenstein-Ingenieure-AG/lrs-editor/assets/88319901/04d57c7d-5a3f-4b3c-a78d-cd5e6cfdf259)

Clicking Ok I get the error:  
![image](https://github.com/Holenstein-Ingenieure-AG/lrs-editor/assets/88319901/9b955f06-d658-452a-99bc-e14c23b81439)
 as there are no geometries in this layer yet. This is the point where I fail. Am I supposed to manually insert my geometries into that table?
If I import a linestring layer with my geometries into my schema, I am not able to choose that in the upper dialog (I guess the table is simply not known to the LRS Editor).

If I ignore this issue and continue to create a basesystem, I get the error message described in #3
