### ISSUE TITLE
Python Error: find_srid when creating basesystem

### ISSUE THREAD

**Issue by e-shirt** [Holenstein-Ingenieure-AG/lrs-editor#3]
When setting up basesystem, I get the following Python error:
```
psycopg2.errors.RaiseException: FEHLER:  find_srid() - could not find the corresponding SRID - is the geometry registered in the GEOMETRY_COLUMNS table?  Is there an uppercase/lowercase mismatch? CONTEXT:  PL/pgSQL-Funktion find_srid(character varying,character varying,character varying) Zeile 17 bei RAISE 
Traceback (most recent call last):
  File "C:\Users/%USER%/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\lrseditor\gui\basesystem.py", line 202, in apply
    if self.pg_conn_bs.srid_find(self.schema_bs, self.cbx_point_class_name.currentText(),
  File "C:\Users/%USER%/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\lrseditor\utils\pg_conn.py", line 73, in srid_find
    cur.execute(query)
  File "C:\PROGRA~1\QGIS33~1.0\apps\Python39\lib\site-packages\psycopg2\extras.py", line 146, in execute
    return super().execute(query, vars)
psycopg2.errors.RaiseException: FEHLER:  find_srid() - could not find the corresponding SRID - is the geometry registered in the GEOMETRY_COLUMNS table?  Is there an uppercase/lowercase mismatch?
CONTEXT:  PL/pgSQL-Funktion find_srid(character varying,character varying,character varying) Zeile 17 bei RAISE
```

Used CRS is EPSG:25832 (ETRS89/ UTM 32N).
CRS is set as project CRS, EPSG code is succesfully added into SRID column in lrs_project table.
I also tested with EPSG:2056, so there seems to be no issue with using another CRS than the tested one.
I don't know my way around code so I cannot tell, if the error is on the plugin side or QGIS or me.
Any help is appreciated.

**Comment by e-shirt** [comment]
So I tried to dig further into the problem. As I understand, the plugin cannot find the srid in the geometry_columns view. As I understand, the srid in that view is taken from my lrs_project  table and should be used to take the CRS data from the spatial_ref_sys table (which I think is created from postgis itself?). The field name is always "srid", the CRS ID is the same in all tables.

Per default the view is put into the public schema, even though the rest of my project is set up in a different schema. I pushed all tables into the public schema, but the error still persists.
At this point, I am clueless again as to why the plugin can not find the srid as it is obviously there.

**Comment by meier-r** [comment]
The plugin is tested with EPSG:25832 and should work with a Base System in your coordinate system. 

Your error indicates, that the provided Point Class of your Base System has a coordinate system the PostGIS-Extension can not identify. For further clarifications, whether your Base System meets the requirements, an export of your database is needed.

The coordinate system of your Base System (Base and Point Class) should be the same as defined in the QGIS-Project and therefore in the LRS-Project (EPSG:25832).
